#ifndef CALOOBJECTS_H
#define CALOOBJECTS_H

struct JetCaloType {
JetCaloType(): pt(-1.), eta(-9.), phi(-9.), mass(-1.), energy(-1.), energyRaw(-1.), ptRaw(-1.), ptUnc(-1.), CSV(-99.), CMVA(-99.), dPhi_met(-99.), cHadE(-1.), nHadE (-1.), eleE(-1.), photonE(-1.), muE(-1.), nEmE(-1.), cEmE(-1.), cmuE(-1.), cHadEFrac(-1.), nHadEFrac(-1.), eleEFrac(-1.), photonEFrac(-1.), muEFrac(-1.), nEmEFrac(-1.), cEmEFrac(-1.), cmuEFrac(-1.), cHadMulti(-1.), nHadMulti(-1.), eleMulti(-1.), photonMulti(-1.), muMulti(-1.), cMulti(-1.), nMulti(-1.), npr(-1.), cHadMultiFrac(-1.), nHadMultiFrac(-1.), eleMultiFrac(-1.), photonMultiFrac(-1.), muMultiFrac(-1.), cMultiFrac(-1.), nMultiFrac(-1.), ptGenJ(-10.), etaGenJ(-4.), phiGenJ(-4.), massGenJ(-10.),ptGen(-10.), etaGen(-4.), phiGen(-4.), massGen(-10.), pdgIdGen(0.), partonFlavour(0), hadronFlavour(0), mother(0), isLoose(false), isTight(false), isTightLepVeto(false), matchBquark(-1), matchLL(-1), isGenMatched(0), isGenMatchedCaloCorr(0), isGenMatchedLLPAccept(0), isGenMatchedCaloCorrLLPAccept(0), radiusLLP(-1000.), xLLP(-10000.), yLLP(-10000.), zLLP(-10000.), radiusLLPCaloCorr(-1000.), xLLPCaloCorr(-10000.), yLLPCaloCorr(-10000.), zLLPCaloCorr(-10000.), xGenb(-10000.), yGenb(-10000.), zGenb(-10000.), xGenbCaloCorr(-10000.), yGenbCaloCorr(-10000.), zGenbCaloCorr(-10000.), isVBFGenMatched(0), ptAllTracks(-1.), ptAllPVTracks(-1.), ptPVTracksMax(-1.), nTracksAll(-1), nTracksPVMax(-1), medianIP2D(-10000.), medianTheta2D(-100.), alphaMax(-100.), betaMax(-100.), gammaMax(-100.), gammaMaxEM(-100.), gammaMaxHadronic(-100.), gammaMaxET(-100.), minDeltaRAllTracks(999.), minDeltaRPVTracks(999.), nPixelHitsMedian(-1.0), nHitsMedian(-1.0), dzMedian(-9999.), dxyMedian(-9999.),
hcalE(-100.), ecalE(-100.), FracCal(-100.), isCaloTag(0),
ptJESUp (-1.), ptJESDown (-1.), ptJER(-1.), ptJERUp (-1.), ptJERDown (-1.), energyJER (-1.), energyJERUp (-1.), energyJERDown (-1.), etaJER (-1.), etaJERUp (-1.), etaJERDown (-1.), JERresolution (-1.), JERsf (-1.), JERsfUp (1.), JERsfDown (-1), JERsmearFactor(-1.), JERsmearFactorUp(-1.), JERsmearFactorDown(-1.), nConstituents (-1), nTrackConstituents (-1),  nTrackConstituentsWithPtLarger0p95(-1), nTrackConstituentsWithTrackDetails(-1), nTrackConstituentsWithTrackDetailsPtLarger0p95(-1), nMatchedGenBquarks(-1), nMatchedGenBquarksCaloCorr(-1), nRecHitsEB(-1), timeRecHitsEB(-100.), timeRMSRecHitsEB(-1.), energyRecHitsEB(-1.), energyErrorRecHitsEB(-1.), xRecHitsEB(-1000.), yRecHitsEB(-1000.), zRecHitsEB(-1000.), radiusRecHitsEB(-1000.), nRecHitsEE(-1), timeRecHitsEE(-100.), timeRMSRecHitsEE(-1.), energyRecHitsEE(-1.), energyErrorRecHitsEE(-1.), xRecHitsEE(-1000.), yRecHitsEE(-1000.), zRecHitsEE(-1000.), radiusRecHitsEE(-1000.), nRecHitsHB(-1), timeRecHitsHB(-100.), timeRMSRecHitsHB(-1.), energyRecHitsHB(-1.), energyErrorRecHitsHB(-1.), xRecHitsHB(-1000.), yRecHitsHB(-1000.), zRecHitsHB(-1000.), radiusRecHitsHB(-1000.), nRecHitsHE(-1), timeRecHitsHE(-100.), timeRMSRecHitsHE(-1.), energyRecHitsHE(-1.), energyErrorRecHitsHE(-1.), xRecHitsHE(-1000.), yRecHitsHE(-1000.), zRecHitsHE(-1000.), radiusRecHitsHE(-1000.), eFracRecHitsEB(-1.), eFracRecHitsEE(-1.), eFracRecHitsHB(-1.), eFracRecHitsHE(-1.),
sig1EB(-1.), sig2EB(-1.), sigAvEB(-1.),tan2thetaEB(-99999999.),ptDEB(-1.),
sig1EE(-1.), sig2EE(-1.), sigAvEE(-1.),tan2thetaEE(-99999999.),ptDEE(-1.),
sig1HB(-1.), sig2HB(-1.), sigAvHB(-1.),tan2thetaHB(-99999999.),ptDHB(-1.),
sig1PF(-1.), sig2PF(-1.), sigAvPF(-1.),tan2thetaPF(-99999999.),ptDPF(-1.),
//LLP calo tagger
sigprob(-1.),
//Additional variables for Beam Halo
    meanEtaEB(-9.),   spreadEtaEB(-1.),
    meanPhiEB(-9.),   spreadPhiEB(-1.),
    meanATLASEB(-9.), spreadATLASEB(-1.),
    meanWeightedEtaEB(-9.),   spreadWeightedEtaEB(-1.),
    meanWeightedPhiEB(-9.),   spreadWeightedPhiEB(-1.),
    meanWeightedATLASEB(-9.), spreadWeightedATLASEB(-1.),
    meanXEB(-9.),   spreadXEB(-1.),
    meanYEB(-9.),   spreadYEB(-1.),
    meanZEB(-9.),   spreadZEB(-1.),
    meanREB(-9.),   spreadREB(-1.),
    meanWeightedXEB(-1000.),   spreadWeightedXEB(-1.),
    meanWeightedYEB(-1000.),   spreadWeightedYEB(-1.),
    meanWeightedZEB(-1000.),   spreadWeightedZEB(-1.),
    meanWeightedREB(-1000.),   spreadWeightedREB(-1.),
    energyEB2CSC(-1.), eFracEB2CSC(-1.),
    energyEB2CSC0p1(-1.), eFracEB2CSC0p1(-1.),
    energyEB2CSC0p04(-1.), eFracEB2CSC0p04(-1.)

{}
    float pt;
    float eta;
    float phi;
    float mass;
    float energy;
    float energyRaw;
    float ptRaw;
    float ptUnc;
    float CSV;
    float CMVA;
    float dPhi_met;
    float cHadE;
    float nHadE;
    float eleE;
    float photonE;
    float muE;
    float nEmE;
    float cEmE;
    float cmuE;
    float cHadEFrac;
    float nHadEFrac;
    float eleEFrac;
    float photonEFrac;
    float muEFrac;
    float nEmEFrac;
    float cEmEFrac;
    float cmuEFrac;
    float cHadMulti;
    float nHadMulti;
    float eleMulti;
    float photonMulti;
    float muMulti;
    float cMulti;
    float nMulti;
    float npr;
    float cHadMultiFrac;
    float nHadMultiFrac;
    float eleMultiFrac;
    float photonMultiFrac;
    float muMultiFrac;
    float cMultiFrac;
    float nMultiFrac;
    float ptGenJ;
    float etaGenJ;
    float phiGenJ;
    float massGenJ;
    float ptGen;
    float etaGen;
    float phiGen;
    float massGen;
    int pdgIdGen;
    int partonFlavour;
    int hadronFlavour;
    int mother;
    bool isLoose;
    bool isTight;
    bool isTightLepVeto;
    bool isCSVL;
    bool isCSVM;
    bool isCSVT;
    int PUId;
    bool PUIdLoose;
    bool PUIdMedium;
    bool PUIdTight;
    float PUDiscriminant;
    int matchBquark;
    int matchLL;
    int isGenMatched;    
    int isGenMatchedCaloCorr;
    int isGenMatchedLLPAccept;
    int isGenMatchedCaloCorrLLPAccept;
    float radiusLLP;
    float xLLP;
    float yLLP;
    float zLLP;
    float radiusLLPCaloCorr;
    float xLLPCaloCorr;
    float yLLPCaloCorr;
    float zLLPCaloCorr;
    float xGenb;
    float yGenb;
    float zGenb;
    float xGenbCaloCorr;
    float yGenbCaloCorr;
    float zGenbCaloCorr;
    int isVBFGenMatched;
    //track, new implementation
    float ptAllTracks;
    float ptAllPVTracks;
    float ptPVTracksMax;
    int   nTracksAll;
    int   nTracksPVMax;
    float medianIP2D;
    float medianTheta2D;
    float alphaMax;
    float betaMax;
    float gammaMax;
    float gammaMaxEM;
    float gammaMaxHadronic;
    float gammaMaxET;
    float minDeltaRAllTracks;
    float minDeltaRPVTracks;
    float nPixelHitsMedian;
    float nHitsMedian;
    float dzMedian;
    float dxyMedian;
    float hcalE;
    float ecalE;
    float FracCal;
    float flightDist2d;
    float flightDist2dError;
    float flightDist3d;
    float flightDist3dError;
    int isCaloTag;
    float ptJESUp;
    float ptJESDown;
    float ptJER;
    float ptJERUp;
    float ptJERDown;
    float energyJER;
    float energyJERUp;
    float energyJERDown;
    float etaJER;
    float etaJERUp;
    float etaJERDown;
    float JERresolution;
    float JERsf;
    float JERsfUp;
    float JERsfDown;
    float JERsmearFactor;
    float JERsmearFactorUp;
    float JERsmearFactorDown;
    int nConstituents;
    int nTrackConstituents;
    int nTrackConstituentsWithPtLarger0p95;
    int nTrackConstituentsWithTrackDetails;
    int nTrackConstituentsWithTrackDetailsPtLarger0p95;
    int nMatchedGenBquarks;
    int nMatchedGenBquarksCaloCorr;
    int nRecHitsEB;
    float timeRecHitsEB;
    float timeRMSRecHitsEB;
    float energyRecHitsEB;
    float energyErrorRecHitsEB;
    float xRecHitsEB;
    float yRecHitsEB;
    float zRecHitsEB;
    float radiusRecHitsEB;

    int nRecHitsEE;
    float timeRecHitsEE;
    float timeRMSRecHitsEE;
    float energyRecHitsEE;
    float energyErrorRecHitsEE;
    float xRecHitsEE;
    float yRecHitsEE;
    float zRecHitsEE;
    float radiusRecHitsEE;

    int nRecHitsHB;
    float timeRecHitsHB;
    float timeRMSRecHitsHB;
    float energyRecHitsHB;
    float energyErrorRecHitsHB;
    float xRecHitsHB;
    float yRecHitsHB;
    float zRecHitsHB;
    float radiusRecHitsHB;
    int nRecHitsHE;
    float timeRecHitsHE;
    float timeRMSRecHitsHE;
    float energyRecHitsHE;
    float energyErrorRecHitsHE;
    float xRecHitsHE;
    float yRecHitsHE;
    float zRecHitsHE;
    float radiusRecHitsHE;

    float eFracRecHitsEB;
    float eFracRecHitsEE;
    float eFracRecHitsHB;
    float eFracRecHitsHE;

    float sig1EB;
    float sig2EB;
    float sigAvEB;
    float tan2thetaEB;
    float ptDEB;
    float sig1EE;
    float sig2EE;
    float sigAvEE;
    float tan2thetaEE;
    float ptDEE;
    float sig1HB;
    float sig2HB;
    float sigAvHB;
    float tan2thetaHB;
    float ptDHB;
    float sig1PF;
    float sig2PF;
    float sigAvPF;
    float tan2thetaPF;
    float ptDPF;

    float sigprob;

    float meanEtaEB;
    float spreadEtaEB;
    float meanPhiEB;
    float spreadPhiEB;
    float meanATLASEB;
    float spreadATLASEB;
    float meanWeightedEtaEB;
    float spreadWeightedEtaEB;
    float meanWeightedPhiEB;
    float spreadWeightedPhiEB;
    float meanWeightedATLASEB; 
    float spreadWeightedATLASEB;
    float meanXEB;   
    float spreadXEB;
    float meanYEB;   
    float spreadYEB;
    float meanZEB;   
    float spreadZEB;
    float meanREB;   
    float spreadREB;
    float meanWeightedXEB;   
    float spreadWeightedXEB;
    float meanWeightedYEB;   
    float spreadWeightedYEB;
    float meanWeightedZEB;   
    float spreadWeightedZEB;
    float meanWeightedREB;   
    float spreadWeightedREB;
    float energyEB2CSC; 
    float eFracEB2CSC;
    float energyEB2CSC0p1;
    float eFracEB2CSC0p1;
    float energyEB2CSC0p04;
    float eFracEB2CSC0p04;

};
#endif
